### ISSUE TITLE
Add new paper

### ISSUE THREAD

**Issue by noveens** [Guang000/Awesome-Dataset-Distillation#10]
Hello maintainers,

Super thanks for maintaining this wonderful resource!
Here's a paper of mine (upcoming at NeurIPS '22) that tries to do data distillation for recommender systems (discrete, heterogeneous, semi-structured data):

[Infinite Recommendation Networks: A Data-Centric Approach](https://www.noveens.com/#neurips_22)
Noveen Sachdeva, Mehak Preet Dhaliwal, Carole-Jean Wu, Julian McAuley
NeurIPS, 2022

It'll be awesome if you could include this in the list.

Thanks!

**Comment by Guang000** [comment]
Thank you for your suggestion. We have added this excellent paper in a new recommender systems subsection.

**Comment by noveens** [comment]
I think there's an error in the name of the paper you just added, but thank you so much for your promptness 😄

**Comment by Guang000** [comment]
Sorry for that. I fixed it.
