### ISSUE TITLE
New papers

### ISSUE THREAD

**Issue by dm-medvedev** [Guang000/Awesome-Dataset-Distillation#19]
Hello maintainers!

I've just found this great repository,  and I wonder if it possible to add two papers of mine:
* [New Properties of the Data Distillation Method When Working With Tabular Data](https://arxiv.org/abs/2010.09839) (Published at [AIST 2020](https://link.springer.com/chapter/10.1007/978-3-030-72610-2_29) conference)
* [Learning to Generate Synthetic Training Data using Gradient Matching and Implicit Differentiation](https://arxiv.org/pdf/2203.08559.pdf) (Published at [AIST 2021](https://link.springer.com/chapter/10.1007/978-3-031-15168-2_12) conference)

Thanks!

**Comment by Guang000** [comment]
Thanks for your kind reminder, I have checked the listed papers, and they are early published papers. I think it could be listed in a new section Tabular data, but the second paper is not suited for the main DD algorithm. What do you think about it?

**Comment by dm-medvedev** [comment]
The second paper is about distillation using GAN in image domain. The idea is very close to the [original paper](https://arxiv.org/pdf/1912.07768.pdf) but with usage of [Gradient Matching](https://arxiv.org/abs/2006.05929). There are also some experiments with Implicit Differentiation. Please tell me why the second article is not suitable for the main DD algorithm? I thought that the article could be placed in the `Distilled Dataset Parametrization` section.

Thanks!
