### ISSUE TITLE
Could DD be applied to object detection?

### ISSUE THREAD

**Issue by zytx121** [Guang000/Awesome-Dataset-Distillation#22]
Hi, @Guang000!  This is the first time I have heard of DD, and I think it is very interesting and has great application value. Has this technology been used for object detection tasks? If not, I want to give it a try.

**Comment by Guang000** [comment]
Of course, there is no dataset distillation algorithm for object detection yet, it will be challenging but worth a try, good luck :).

**Comment by zytx121** [comment]
Thank you for your suggestion!
