### ISSUE TITLE
Is there any user-friendly toolkit for dataset distillation?

### ISSUE THREAD

**Issue by Silung** [Guang000/Awesome-Dataset-Distillation#25]
I need to use dataset distillation to preliminarily validate my ideas, but I haven't found any readily available toolkit.

**Comment by Guang000** [comment]
Thank you for your question, there are many available codes in this repo, please click the :octocat: for details.
For example, the most used methods, DC (https://github.com/VICO-UoE/DatasetCondensation) and MTT (https://github.com/georgecazenavette/mtt-distillation).

**Comment by Silung** [comment]
Thank you, I will try them : )
