### ISSUE TITLE
open source codes of these papers

### ISSUE THREAD

**Issue by suizhihao** [Guang000/Awesome-Dataset-Distillation#37]
I am delighted to observe the compilation of continuously updated papers in the field of data set distillation. However, I have noticed that compared to other remarkable awesome-XX code repositories, a majority of these papers, particularly those related to privacy, lack accompanying codes. This absence hinders the reproducibility of experiments and verification of their authenticity. Could you kindly request the respective authors to upload their codes? This would significantly enhance the impact of the project. Thank you!

**Comment by Guang000** [comment]
Thank you for your feedback! Opening source code is essential for fostering research transparency and supporting experimental reproducibility. Adopting this practice will increase the project's influence. We are grateful for your suggestion and will consider it for our future compilations.
