### ISSUE TITLE
About the paper Privacy for Free: How does Dataset Condensation Help Privacy? (Tian Dong et al., ICML 2022) 

### ISSUE THREAD

**Issue by suizhihao** [Guang000/Awesome-Dataset-Distillation#38]
Dear repo maintainer :

[Privacy for Free: How does Dataset Condensation Help Privacy?](https://arxiv.org/abs/2206.00240) (Tian Dong et al., ICML 2022) 

This paper has been proved to have a number of errors, and many researchers have published relevant papers to refute it in the follow-up to this paper. I think it is necessary for you to attach the relevant papers, otherwise it will easily mislead researchers who are new to this field.

Best regards.

**Comment by Guang000** [comment]
Thank you for your advice, I have added the related paper in this repo.
