### ISSUE TITLE
New papers

### ISSUE THREAD

**Issue by Liu-Hy** [Guang000/Awesome-Dataset-Distillation#41]
Hello maintainers:

Thank you for maintaining this wonderful repo! I wonder if it would be possible to add two new papers of mine:
1. [Dataset Distillation via the Wasserstein Metric](https://arxiv.org/abs/2311.18531) This paper employs the Wasserstein metric for distribution matching
2. [Towards Adversarially Robust Dataset Distillation by Curvature Regularization](https://arxiv.org/abs/2403.10045) This paper incorparates adversarial robustness into the distilled data by curvature regularization, which may fit into the "trustworthy" section.

Best,
Haoyang

**Comment by Guang000** [comment]
Thank you for your contribution, I will add them to the repo and hope you can add the corresponding open-source code.

**Comment by Liu-Hy** [comment]
Thank you! Sure, I will do this.
