### ISSUE TITLE
Add new paper

### ISSUE THREAD

**Issue by JLUssh** [Guang000/Awesome-Dataset-Distillation#54]
Hello maintainers:

Thank you for maintaining this wonderful repo! I wonder if it would be possible to add one new papers of mine:

[DCFL: Non-IID Awareness Dataset Condensation Aided Federated Learning](https://ieeexplore.ieee.org/document/10650791) (Publised at IJCNN 2024). In this paper, we propose a fine-grained approach to utilizing condensed data from the perspective of client complementarity and provide guidelines for the transfer of condensed data among clients. I think this paper can be categorized under Federated Learning, and I sincerely thank you for your excellent work, which has inspired our research before it has been published.

Thanks!

**Comment by Guang000** [comment]
Of course, thanks for the contribution.
