### ISSUE TITLE
Two related papers

### ISSUE THREAD

**Issue by yongchao97** [Guang000/Awesome-Dataset-Distillation#7]
Hello, Bo, Guang, and Tongzhou.

Thanks for this fantastic repository! The two papers below, in my opinion, should be included in this repository.

1. [Optimizing Millions of Hyperparameters by Implicit Differentiation](https://arxiv.org/abs/1911.02590): This paper proposes the use of Implicit Differentiation, a general gradient-based hyperparameter optimization method, for dataset distillation tasks (Section 5.3).
2. [On Implicit Bias in Overparameterized Bilevel Optimization](https://proceedings.mlr.press/v162/vicol22a.html): The dataset distillation is covered in this study from a general bi-level optimization perspective. It provides some valuable insights into the implicit bias in dataset distillation. We may want to create a "Theory" section for this paper.

Best,
Yongchao

**Comment by Guang000** [comment]
Hi, Yongchao.

Thank you for your valuable suggestion! I will discuss it with Bo and Tongzhou. We will reply as soon as possible.

Best,
Guang

**Comment by Guang000** [comment]
After discussion, we decided to add them to the Optimization section. Thanks for your contribution.
