### ISSUE TITLE
Add recent ICLR Submission?

### ISSUE THREAD

**Issue by yongchao97** [Guang000/Awesome-Dataset-Distillation#9]
Hello, Bo, Guang, and Tongzhou,

I wonder if you guys want to include some new ICLR submission. Here are some related links but maybe more.

[Memory-efficient Trajectory Matching for Scalable Dataset Distillation](https://openreview.net/pdf?id=dN70O8pmW8), 
[Dataset Condensation with Latent Space Knowledge Factorization and Sharing](https://openreview.net/pdf?id=ab2mCzEPwqK),
[Differentially Private Dataset Condensation](https://openreview.net/pdf?id=H8XpqEkbua_),
[Faster Hyperparameter Search for GNNs via Calibrated Dataset Condensation](https://openreview.net/pdf?id=ohQPU2G3r3C), 
[Towards Robust Dataset Learning](https://openreview.net/pdf?id=OA4o8yKW3q),
[Lossless Dataset Compression via Dataset Quantization](https://openreview.net/pdf?id=zRCEbtS646c)

BTW, could you change my paper citation to the following? (I have made a change in the OpenReview, but has not been reflected yet). 

@inproceedings{zhou2022dataset,
  title={Dataset Distillation using Neural Feature Regression},
  author={Zhou, Yongchao and Nezhadarya, Ehsan and Ba, Jimmy},
  booktitle={Proceedings of the Advances in Neural Information Processing Systems (NeurIPS)},
  year={2022}
}

Thanks,
Yongchao

**Comment by Guang000** [comment]
Hi, thank you for your valuable advice. We will add these papers.
I have changed your paper citation to the correct format.

**Comment by SsnL** [comment]
Hey Yongchao and Guang, sorry for the late reply, but I don't think we should add anonymous submissions. Ideally this should be a collection of good DD papers, not a collection of every DD paper. I'm not saying that these submissions are good. (In fact, many are great!) But I feel that we should give them some time to be better evaluated and perceived by the community, at least waiting until they become unanonymized via arXiv or acceptance.

**Comment by PatrickZH** [comment]
Hi all, I agree with Tongzhou. The main goal of repo is to provide beginners with a time-saving road map. The papers must be reviewed and selected.
